import asyncio
import sys
from typing import TypedDict, Annotated, List, Literal
from langgraph.graph import StateGraph, END
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from dotenv import load_dotenv
load_dotenv()

# MCP Client Imports
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

# ==========================================
# 1. STATE & SYSTEM PROMPTS
# ==========================================

class CICDState(TypedDict):
    repo_url: str
    branch: str
    scan_passed: bool
    image_tag: str
    pipeline_log: Annotated[List[str], "append"]
    messages: Annotated[List[any], "append"]

llm = ChatOpenAI(model="gpt-4o", temperature=0)

# System Prompts define the constraints for each specialized agent
# System Prompts define the strict constraints and personas for each specialized agent
PROMPTS = {
    "analyst": """You are the Lead CI/CD Change Analyst. 
Your objective is to analyze incoming code commits and determine the scope of changes.
RULES:
1. Use the checkout_github_repo tool to retrieve the code.
2. Identify which files were modified. 
3. Output a clear summary of the changes before passing the state forward. DO NOT attempt to run scans yourself.""",

    "security": """You are the Principal Security Auditor. 
Your objective is to enforce strict zero-trust security compliance.
RULES:
1. You MUST use the run_security_scan tool to audit the codebase.
2. If the scan returns 'FAILED', you are strictly forbidden from passing the pipeline. 
3. If a vulnerability is found, you MUST use the apply_code_patch tool to fix the vulnerable dependency.
4. After applying the patch, summarize the fix in your final output.""",

    "qa": """You are the Senior Automation QA Engineer.
Your objective is to guarantee code reliability through testing.
RULES:
1. Use the execute_unit_tests tool to run the test suite.
2. Analyze the test coverage and pass/fail ratio.
3. If tests fail, output the exact error trace and halt. If they pass, confirm the code is ready for packaging.""",

    "build": """You are the Release Engineering Agent.
Your objective is to construct a reproducible, immutable Docker container.
RULES:
1. Use the package_and_containerize tool to build the image.
2. You must extract and output the final Docker Image Tag generated by the tool. This tag is critical for downstream testing.""",

    "automation": """You are the Integration Test Agent.
Your objective is to validate the compiled container in a sandbox.
RULES:
1. Use the execute_automation_tests tool, passing the image tag you received from the Build Agent.
2. Verify that UI and API endpoints are responding correctly before approving for release.""",

    "release": """You are the Deployment Manager Agent.
Your objective is to safely route validated artifacts to the UAT environment.
RULES:
1. Use the deploy_to_uat tool using the validated image tag.
2. Confirm the Kubernetes pods are healthy. If successful, declare the pipeline complete."""
}

# ==========================================
# 2. ASYNC GRAPH NODES (THE AGENTS)
# ==========================================
# In a full LangChain/MCP integration, tools are dynamically loaded via the session.
# For this PoV, we simulate the tool execution node dynamically calling the MCP client.

async def stage_checkout(state: CICDState, mcp_session: ClientSession):
    print("🚀 [STAGE 1] Agent Analyst: Requesting Git Checkout...")
    # The LLM reasons, decides to use the tool, and the MCP session executes it
    result = await mcp_session.call_tool("checkout_github_repo", {"repo_url": state["repo_url"], "branch": state["branch"]})
    return {"pipeline_log": [f"CHECKOUT: {result.content[0].text}"]}

async def stage_scan_and_patch(state: CICDState, mcp_session: ClientSession):
    print("🛡️ [STAGE 2] Security Agent: Initiating Code & Dependency Scan...")
    scan_result = await mcp_session.call_tool("run_security_scan", {"target_dir": "./workspace"})
    scan_text = scan_result.content[0].text
    
    if "FAILED" in scan_text:
        print(f"   ❌ Vulnerability Detected: {scan_text}")
        print("   🔧 [SELF-HEALING] Security Agent automatically generating and applying patch...")
        
        # Agent dynamically uses the patch tool
        patch_result = await mcp_session.call_tool("apply_code_patch", {
            "file_path": "requirements.txt", 
            "patch_content": "requests>=2.31.0"
        })
        print(f"   ✅ Patch Applied: {patch_result.content[0].text}")
        return {"scan_passed": True, "pipeline_log": ["SCAN FAILED -> AUTOPATCHED -> SCAN PASSED"]}
        
    return {"scan_passed": True, "pipeline_log": ["SCAN PASSED: Clean codebase."]}

async def stage_unit_test(state: CICDState, mcp_session: ClientSession):
    print("🧪 [STAGE 3] QA Agent: Executing Unit Tests...")
    result = await mcp_session.call_tool("execute_unit_tests", {"test_suite": "pytest tests/"})
    return {"pipeline_log": [f"UNIT TESTS: {result.content[0].text}"]}

async def stage_package_containerize(state: CICDState, mcp_session: ClientSession):
    print("📦 [STAGE 4] Build Agent: Packaging & Containerizing...")
    result = await mcp_session.call_tool("package_and_containerize", {"app_name": "agentic-pov"})
    output = result.content[0].text
    image_tag = output.split("Tag: ")[1] if "Tag: " in output else "latest"
    return {"image_tag": image_tag, "pipeline_log": [f"BUILD: {output}"]}

async def stage_automation_test(state: CICDState, mcp_session: ClientSession):
    print("🤖 [STAGE 5] QA Agent: Executing UI/API Automation...")
    result = await mcp_session.call_tool("execute_automation_tests", {"image_tag": state.get("image_tag", "latest")})
    return {"pipeline_log": [f"AUTOMATION: {result.content[0].text}"]}

async def stage_deploy_uat(state: CICDState, mcp_session: ClientSession):
    print("☁️ [STAGE 6] Release Manager: Deploying to UAT...")
    result = await mcp_session.call_tool("deploy_to_uat", {"image_tag": state.get("image_tag", "latest")})
    return {"pipeline_log": [f"DEPLOY: {result.content[0].text}"]}

# ==========================================
# 3. GRAPH ASSEMBLY & MCP ORCHESTRATION
# ==========================================

async def run_agentic_pipeline(repo_url: str, branch: str):
    # Setup the subprocess parameters to launch your mcp_server.py
    server_params = StdioServerParameters(
    command=sys.executable,
    args=["-u", "mcp_server2.py"], 
    env=None
    )

    # Initialize the MCP connection over stdio
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            
            # Wrap node functions to inject the active MCP session
            workflow = StateGraph(CICDState)
            workflow.add_node("checkout", lambda state: asyncio.run_coroutine_threadsafe(stage_checkout(state, session), asyncio.get_running_loop()).result())
            workflow.add_node("scan", lambda state: asyncio.run_coroutine_threadsafe(stage_scan_and_patch(state, session), asyncio.get_running_loop()).result())
            workflow.add_node("unit_test", lambda state: asyncio.run_coroutine_threadsafe(stage_unit_test(state, session), asyncio.get_running_loop()).result())
            workflow.add_node("package", lambda state: asyncio.run_coroutine_threadsafe(stage_package_containerize(state, session), asyncio.get_running_loop()).result())
            workflow.add_node("automation", lambda state: asyncio.run_coroutine_threadsafe(stage_automation_test(state, session), asyncio.get_running_loop()).result())
            workflow.add_node("deploy", lambda state: asyncio.run_coroutine_threadsafe(stage_deploy_uat(state, session), asyncio.get_running_loop()).result())

            workflow.set_entry_point("checkout")
            workflow.add_edge("checkout", "scan")
            workflow.add_edge("scan", "unit_test") # Self-healing handles the loop internally now
            workflow.add_edge("unit_test", "package")
            workflow.add_edge("package", "automation")
            workflow.add_edge("automation", "deploy")
            workflow.add_edge("deploy", END)

            pipeline = workflow.compile()
            
            initial_state = {
                "repo_url": repo_url,
                "branch": branch,
                "scan_passed": False,
                "image_tag": "",
                "pipeline_log": []
            }
            
            print("\n" + "="*50)
            print("INITIALIZING AGENTIC CI/CD PIPELINE")
            print("="*50 + "\n")
            
            final_state = pipeline.invoke(initial_state)
            
            print("\n" + "="*50)
            print("🎉 PIPELINE COMPLETED SUCCESSFULLY")
            print(f"📦 Final Image Tag: {final_state['image_tag']}")
            print("="*50 + "\n")
            
            return final_state

if __name__ == "__main__":
    # Execute the asynchronous graph
    #asyncio.run(run_agentic_pipeline("https://github.com/enterprise/payment-gateway", "feature/auth-update"))
    asyncio.run(run_agentic_pipeline("https://github.com/vivek9810tal/catalog-intelligence-engine.git", "main"))